# Generated by Django 3.2.9 on 2021-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('director', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
    ]
